package main

import (
  "github.com/btcsuite/btcutil"
  "time"
  "io/ioutil"
  "os"
)

func main() {
  certFile := "/tmp/rpc.cert"
  keyFile := "/tmp/rpc.key"

  org := "btcd autogenerated cert"
  validUntil := time.Now().Add(10 * 365 * 24 * time.Hour)
  cert, key, err := btcutil.NewTLSCertPair(org, validUntil, []string{"btcd"})
  if err != nil {
    return
  }

  // Write cert and key files.
  if err = ioutil.WriteFile(certFile, cert, 0666); err != nil {
    return
  }
  if err = ioutil.WriteFile(keyFile, key, 0600); err != nil {
    os.Remove(certFile)
    return
  }
}
